CREATE TABLE employees
(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    CONSTRAINT pk_employees PRIMARY KEY (employee_id)
);